name: trello-cli
base: core18
version: '0.0.1'
summary: Command Line Interface for Trello 
description: |
  trello-cli allows you to query to find informations about your Trello Data
  trello cli can list boards, lanes and show cards by user

grade: devel
confinement: devmode

parts:
  trello-cli:
    plugin: python
    python-version: python3
    python-packages:
      - py-trello
    source: .

apps:
  trello-cli:
    command: bin/trello-cli
